export const Bienes = [
    {
        id: 2,
        coor_reg: 'Jalisco',
        t_bien: 'Bienes Inmuebles',
        subtipo: 'Departamento',
        b_numero: 7894,
        b_descripcion: 'Departamento en Avenida Revolución Número 502, Colonia Moderna, Guadalajara, Jalisco.',
        ubicacion_almacen: 'Guadalajara',
        seleccionado: true,
        imagen: '../../../../assets/imgen/casa.jpg',
    },
    {
        id: 3,
        coor_reg: 'Quintana Roo',
        t_bien: 'Bienes Inmuebles',
        subtipo: 'Terreno',
        b_numero: 564,
        b_descripcion: 'Terreno de 800 m2 en Playa del Carmen, Quintana Roo.',
        ubicacion_almacen: 'Playa del Carmen',
        seleccionado: false,
        imagen: '../../../../assets/imgen/casa.jpg',
    },
    {
        id: 4,
        coor_reg: 'Nuevo León',
        t_bien: 'Bienes Inmuebles',
        subtipo: 'Local Comercial',
        b_numero: 1298,
        b_descripcion: 'Local en Calle Hidalgo Número 203, Monterrey, Nuevo León.',
        ubicacion_almacen: 'Monterrey',
        seleccionado: true,
        imagen: '../../../../assets/imgen/casa2.png',
    },
];