export const Bienes = [
    {
        id: 2,
        coor_reg: 'Jalisco',
        t_bien: 'Bienes Inmuebles',
        subtipo: 'Departamento',
        b_numero: 7894,
        b_descripcion: 'Departamento en Av. Revolución No. 502, Col. Moderna, Guadalajara, Jalisco.',
        ubicacion_almacen: 'Guadalajara',
        seleccionado: true,
        imagen: '../../../../assets/imgen/casa.jpg',
    },
    {
        id: 3,
        coor_reg: 'Quintana Roo',
        t_bien: 'Bienes Inmuebles',
        subtipo: 'Terreno',
        b_numero: 564,
        b_descripcion: 'Terreno de 800 m2 en Playa del Carmen, Quintana Roo.',
        ubicacion_almacen: 'Playa del Carmen',
        seleccionado: false,
        imagen: '../../../../assets/imgen/casa.jpg',
    },
    {
        id: 4,
        coor_reg: 'Nuevo León',
        t_bien: 'Bienes Inmuebles',
        subtipo: 'Local Comercial',
        b_numero: 1298,
        b_descripcion: 'Local en Calle Hidalgo No. 203, Monterrey, Nuevo León.',
        ubicacion_almacen: 'Monterrey',
        seleccionado: true,
        imagen: '../../../../assets/imgen/casa2.png',
    },
    {
      id: 5,
      coor_reg: 'Distrito Federal',
      t_bien: 'Bienes Inmuebles',
      subtipo: 'Oficina',
      b_numero: 2345,
      b_descripcion: 'Oficina en Paseo de la Reforma No. 1001, Col. Juárez, Ciudad de México.',
      ubicacion_almacen: 'Ciudad de México',
      seleccionado: true,
      imagen: '../../../../assets/imgen/casa.jpg',
  },
  {
      id: 6,
      coor_reg: 'Puebla',
      t_bien: 'Bienes Inmuebles',
      subtipo: 'Casa Habitación',
      b_numero: 876,
      b_descripcion: 'Casa en Calle las Flores No. 45, Col. San Pedro, Puebla, Puebla.',
      ubicacion_almacen: 'Puebla',
      seleccionado: false,
      imagen: '../../../../assets/imgen/casa2.png',
  },
  {
      id: 7,
      coor_reg: 'Sinaloa',
      t_bien: 'Bienes Inmuebles',
      subtipo: 'Rancho',
      b_numero: 653,
      b_descripcion: 'Rancho de 50 hectáreas en Culiacán, Sinaloa.',
      ubicacion_almacen: 'Culiacán',
      seleccionado: true,
      imagen: '../../../../assets/imgen/casa.jpg',
  },
  {
      id: 8,
      coor_reg: 'Guanajuato',
      t_bien: 'Bienes Inmuebles',
      subtipo: 'Departamento',
      b_numero: 123,
      b_descripcion: 'Departamento en Calle Madero No. 789, Col. Centro, León, Guanajuato.',
      ubicacion_almacen: 'León',
      seleccionado: false,
      imagen: '../../../../assets/imgen/casa2.png',
  }
];



